### ISSUE TITLE
PDF generation code

### ISSUE THREAD

**Issue by leebrian** [ablwr/halt-and-catch-fire-syllabus#3]
Great project and site. I'm trying to find the code that you use to generate the pdf version of the site that you have in your repo at https://github.com/ablwr/halt-and-catch-fire-syllabus/blob/main/HaltAndCatchFireSyllabus.pdf

I'm interested in jekyll plugins that do a good job generating PDFs and I like how your site offers both html and pdf versions.

**Comment by ablwr** [comment]
Hi @leebrian!

I didn't do anything fancy or automated, and the script doesn't even have a cute bash loop, but I generated it like this: `pandoc -f markdown -t pdf pandoc-header.md _classes/01.md _classes/02.md _classes/03.md _classes/04.md _classes/05.md _classes/06.md _classes/07.md _classes/08.md _classes/09.md _classes/10.md _classes/11.md _classes/12.md _classes/13.md _classes/14.md _classes/15.md pandoc-header.md -o syllabus.pdf --pdf-engine=xelatex`

It does not automatically update if I update the site. I'm trying to think of if I have done automatic PDF generation through Jekyll before... I know there's a plug-in for it, but I think I've always just done it manually using bash when necessary!

**Comment by leebrian** [comment]
Thanks so much @ablwr. This script is helpful and similar to something I do too. Surprisingly, I haven't found an easy jekyll plugin yet, but think it's do to me just not googling well. I appreciate you taking the time to answer.
